data:
  path: Processed_Data
  train_file: X_train_processed.csv
  test_file: X_test_processed.csv

submit:
  path: Data
  file: submission.csv

model:
  save_path: model
  load_path: null

train:
  seed: 42
  num_epochs: 10
  patience: 10000
  batch_size: 512