train:
  lr: 0.001
  num_epochs: 5

data:
  batch_size: 256
  data_path: Data/train.csv
  submission_path: Data/submission.csv
  train_path: Processed_Data/train_df.pkl
  test_path: Processed_Data/test_df.pkl
  vocab_path: Processed_Data/vocab_sizes.pkl
  encoder_path: Processed_Data/label_encoders.pkl

model:
  load_path: model/din_model.pth
  save_path: model/din_model.pth
  embed_dim: 64
  max_seq_len: 50